// ----------------------------------------------------------------------------------
// Microsoft Developer & Platform Evangelism
// 
// Copyright (c) Microsoft Corporation. All rights reserved.
// 
// THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
// EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
// OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
// ----------------------------------------------------------------------------------
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
// ----------------------------------------------------------------------------------

// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.SharedAccessSignatureService.#CreateContainer(System.Net.Http.HttpRequestMessage,System.String,System.String)", Justification = "If disposed the HttpMessage is no longer valid for the rest of the handler chains")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.SharedAccessSignatureService.#DeleteContainer(System.String)", Justification = "If disposed the HttpMessage is no longer valid for the rest of the handler chains")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.SharedAccessSignatureService.#GetContainerProperties(System.String)", Justification = "If disposed the HttpMessage is no longer valid for the rest of the handler chains")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.SharedAccessSignatureService.#GetContainerSharedAccessSignature(System.String,System.String)", Justification = "If disposed the HttpMessage is no longer valid for the rest of the handler chains")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.SharedAccessSignatureService.#WebException(System.String,System.Net.HttpStatusCode)", Justification = "If disposed the HttpMessage is no longer valid for the rest of the handler chains")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.Models.CloudBlob.#Uri", Justification = "Web API cannot serialize Uri correctly")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.Security.FuncBasedOperationHandler.#OnHandle(System.Net.Http.HttpRequestMessage)", Justification = "If disposed the HttpMessage is no longer valid for the rest of the handler chains")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.Models.CloudBlobContainerListResponse.#Containers", Justification = "Array is needed for serialization purposes")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.Models.CloudBlobContainer.#Url", Justification = "Web API cannot serialize Uri correctly")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.Helpers.Extensions.#StorageException(System.Net.HttpStatusCode,System.String,System.String)", Justification = "If disposed the HttpMessage is no longer valid for the rest of the handler chains")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.Helpers.Extensions.#CloneContent(System.Net.Http.HttpContent,System.String)", Justification = "If disposed the HttpMessage is no longer valid for the rest of the handler chains")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.Helpers.CredentialExtensions.#GetCanonicalizedResourceVersion2(System.Uri,System.String)", Justification = "Azure Storage requires headers' canonicalization to be lowercase")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.Handlers.StorageProxyHandler.#GetAzureStorageResponse(System.Uri,System.Net.Http.HttpRequestMessage)", Justification = "If disposed the HttpMessage is no longer valid for the rest of the handler chains")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.SharedAccessSignatureService.#GetBlobSharedAccessSignature(System.String,System.String,System.String)", Justification = "If disposed the HttpMessage is no longer valid for the rest of the handler chains")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.QueuesProxyService.#HandleDelete(System.Net.Http.HttpRequestMessage,System.String)", Justification = "Cannot be static as it is a WEB API method. It just would not be called")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.QueuesProxyService.#HandleGet(System.Net.Http.HttpRequestMessage,System.String)", Justification = "Cannot be static as it is a WEB API method. It just would not be called")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.QueuesProxyService.#HandleMerge(System.Net.Http.HttpRequestMessage,System.String)", Justification = "Cannot be static as it is a WEB API method. It just would not be called")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.QueuesProxyService.#HandlePost(System.Net.Http.HttpRequestMessage,System.String)", Justification = "Cannot be static as it is a WEB API method. It just would not be called")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.QueuesProxyService.#HandlePut(System.Net.Http.HttpRequestMessage,System.String)", Justification = "Cannot be static as it is a WEB API method. It just would not be called")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.TablesProxyService.#HandleDelete(System.Net.Http.HttpRequestMessage,System.String)", Justification = "Cannot be static as it is a WEB API method. It just would not be called")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.TablesProxyService.#HandleGet(System.Net.Http.HttpRequestMessage,System.String)", Justification = "Cannot be static as it is a WEB API method. It just would not be called")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.TablesProxyService.#HandleMerge(System.Net.Http.HttpRequestMessage,System.String)", Justification = "Cannot be static as it is a WEB API method. It just would not be called")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.TablesProxyService.#HandlePost(System.Net.Http.HttpRequestMessage,System.String)", Justification = "Cannot be static as it is a WEB API method. It just would not be called")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.TablesProxyService.#HandlePut(System.Net.Http.HttpRequestMessage,System.String)", Justification = "Cannot be static as it is a WEB API method. It just would not be called")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.SasCloudBlobContainerListResponse.#Containers", Justification = "Array is needed for serialization purposes")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Microsoft.WindowsAzure.Samples.CloudServices.Storage.SasCloudBlobContainer.#Url", Justification = "Web API cannot serialize Uri correctly")]
